// Generated by CoffeeScript 1.9.3
(function() {
  var CheckError, Emulator, genetics, parserlib, ref, speclib;

  ref = require('./emulator'), Emulator = ref.Emulator, CheckError = ref.CheckError;

  parserlib = require('./asm-parser');

  speclib = require('./spec');

  genetics = require('./genetics');

  exports.Emulator = Emulator;

  exports.CheckError = CheckError;

  exports.SyntaxError = parserlib.SyntaxError;

  exports.genetics = genetics;

  exports.parseProgram = parserlib.parse;

  exports.parseSpec = speclib.parse;

}).call(this);
